services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-auth_demo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-showcase}
      - POSTGRES_USER=${POSTGRES_USER:-showcase}
    ports:
      - '5432'
    env_file:
      - .env
