spring.application.name=auth_demo

application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.access-expiration=${JWT_EXPIRATION:300000}
application.security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:900000}

spring.datasource.url=jdbc:${POSTGRES_URL:postgresql://localhost:5432/auth_demo}
spring.datasource.username=${POSTGRES_USER:showcase}
spring.datasource.password=${POSTGRES_PASSWORD:showcase}
spring.jpa.hibernate.ddl-auto=update

# Configuración de BD H2 en memoria para tests
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop