spring.application.name=auth_demo

application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

spring.datasource.url=jdbc:${POSTGRES_URL:postgresql://localhost:5432/auth_demo}
spring.datasource.username=${POSTGRES_USER:showcase}
spring.datasource.password=${POSTGRES_PASSWORD:showcase}
spring.jpa.hibernate.ddl-auto=update
